# Generated by Django 3.1.7 on 2021-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210402_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Economy', 'Economy'), ('International', 'International'), ('News', 'News'), ('Music', 'Music'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Health', 'Health'), ('Select a category', None)], default='Select a category', max_length=50),
        ),
    ]
