# Generated by Django 3.1.7 on 2021-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210402_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[(None, 'Select a category'), ('Food', 'Food'), ('Economy', 'Economy'), ('International', 'International'), ('News', 'News'), ('Music', 'Music'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Health', 'Health')], max_length=50),
        ),
    ]
