# Generated by Django 3.1.7 on 2021-04-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
